In [9]:
import numpy as np
import random as rd

In [10]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [42]:
rd.random()

0.8722070585401175

In [43]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])